# Generated by Django 2.2.12 on 2020-07-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60, null=True)),
                ('brand_name', models.CharField(max_length=60, null=True)),
                ('dosage_type', models.CharField(max_length=60, null=True)),
                ('dosage_form', models.CharField(max_length=60, null=True)),
                ('schedule_type', models.CharField(max_length=60, null=True)),
                ('sheif_life', models.IntegerField(null=True)),
                ('speciality', models.CharField(max_length=70, null=True)),
                ('HSN_CODE', models.CharField(max_length=50, null=True)),
                ('drug_indication', models.CharField(max_length=70, null=True)),
                ('warning', models.CharField(max_length=100, null=True)),
                ('gst', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generic_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=120)),
                ('generic_strength', models.IntegerField()),
                ('generic_unit', models.CharField(max_length=120)),
                ('drug_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drug_master.Drug_Master')),
            ],
        ),
    ]
