# Generated by Django 2.2.12 on 2020-07-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drug_master', '0003_auto_20200703_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic_information',
            name='drug_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug', to='Drug_master.Drug_Master'),
        ),
    ]
